import { Input, MetricCard } from '../components/ui/PageParts'
import type { Dispatch, FormEvent, SetStateAction } from 'react'
import type { Alert, CreateOrderForm, Driver, Order, OrdersListFilter, Screen, Trip } from '../types'

interface DashboardPageProps {
  orders: Order[]
  activeTrips: Trip[]
  completedTrips: Trip[]
  unresolvedAlerts: Alert[]
  trips: Trip[]
  drivers: Driver[]
  setScreen: (screen: Screen) => void
  setSelectedTripId: Dispatch<SetStateAction<number | null>>
  handleApproveTrip: (tripId?: number) => Promise<void>
  form: CreateOrderForm
  setForm: Dispatch<SetStateAction<CreateOrderForm>>
  handleCreateOrder: (event: FormEvent<HTMLFormElement>) => Promise<void>
  rawOrderText: string
  setRawOrderText: Dispatch<SetStateAction<string>>
  handleIngestRawOrder: () => Promise<void>
  approvalMode: string
  isLoading: boolean
  openOrdersWithFilter: (filter: OrdersListFilter) => void
  actionError: string
}

function DashboardPage({
  orders,
  activeTrips,
  completedTrips,
  unresolvedAlerts,
  trips,
  drivers,
  setScreen,
  setSelectedTripId,
  handleApproveTrip,
  form,
  setForm,
  handleCreateOrder,
  rawOrderText,
  setRawOrderText,
  handleIngestRawOrder,
  approvalMode,
  isLoading,
  openOrdersWithFilter,
  actionError,
}: DashboardPageProps) {
  const totalProfit = trips.reduce((sum, trip) => sum + (trip.finance?.profit ?? 0), 0)
  return (
    <div className="p-4 sm:p-6 lg:p-8 flex flex-col xl:flex-row gap-6 lg:gap-8 min-w-0">
      <div className="flex-1 space-y-8">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <MetricCard
            title="Active Trips"
            value={activeTrips.length}
            sub={`${drivers.filter((driver) => driver.availability).length} drivers available · tap for orders`}
            icon="navigation"
            onClick={() => openOrdersWithFilter('active')}
          />
          <MetricCard title="Critical Alerts" value={unresolvedAlerts.length} sub="Action required" icon="priority_high" danger />
          <MetricCard
            title="Completed (24h)"
            value={completedTrips.length}
            sub="System snapshot · tap for orders"
            icon="done_all"
            onClick={() => openOrdersWithFilter('completed')}
          />
          <MetricCard title="Profit Snapshot" value={`$${Math.round(totalProfit)}`} sub="Backend finance engine" icon="attach_money" />
        </div>

        <section>
          <div className="flex items-center justify-between mb-6">
            <h3 className="text-lg font-bold tracking-tight">Auto Created Orders</h3>
            <div className="flex items-center gap-3">
              <span className="px-3 py-1 rounded-full bg-surface-container-low text-[11px] font-bold uppercase tracking-wider">Approval: {approvalMode}</span>
              <button
                onClick={() => openOrdersWithFilter('all')}
                className="text-primary text-xs font-bold flex items-center gap-1 hover:underline"
              >
                View All <span className="material-symbols-outlined text-sm">chevron_right</span>
              </button>
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {orders.slice(0, 4).map((order) => (
              <div key={order.id} className="w-full min-w-0 bg-surface-container-lowest p-5 rounded-xl shadow-sm border border-black/5 flex flex-col">
                <div className="flex justify-between items-start mb-4">
                  <div className="flex flex-col gap-1">
                    <span className="px-2 py-0.5 bg-surface-container-low rounded text-[9px] font-bold text-on-surface-variant uppercase w-fit">ID: SG-{order.id}</span>
                    <span className="text-[10px] font-bold text-on-tertiary-container uppercase tracking-tight flex items-center gap-1">
                      <span className="material-symbols-outlined text-[12px]">auto_awesome</span>
                      Auto Generated by AI
                    </span>
                  </div>
                  <span className="w-2 h-2 rounded-full bg-tertiary-fixed-dim" />
                </div>
                <div className="space-y-3 mb-4">
                  <div className="flex gap-3">
                    <div className="flex flex-col items-center">
                      <span className="w-2 h-2 rounded-full border-2 border-primary" />
                      <div className="w-[1px] h-4 bg-outline-variant my-1" />
                      <span className="material-symbols-outlined text-primary text-[14px]">location_on</span>
                    </div>
                    <div className="flex-1">
                      <p className="text-[10px] text-on-surface-variant font-medium">Pickup</p>
                      <p className="text-xs font-bold">{order.pickupLocation}</p>
                      <div className="h-4" />
                      <p className="text-[10px] text-on-surface-variant font-medium">Drop</p>
                      <p className="text-xs font-bold">{order.dropLocation}</p>
                    </div>
                  </div>
                </div>
                <div className="mt-auto border-t border-black/5 pt-4">
                  <div className="flex items-center justify-between mb-4">
                    <div>
                      <p className="text-[10px] text-on-surface-variant">Load Weight</p>
                      <p className="text-xs font-bold">{order.load}</p>
                    </div>
                    <div className="text-right">
                      <p className="text-[10px] text-on-surface-variant">Date</p>
                      <p className="text-xs font-bold">{order.date}</p>
                    </div>
                  </div>
                  <div className="space-y-2">
                    <p className="text-[11px] text-on-surface-variant italic text-center">Ready for Approval</p>
                    <button
                      onClick={() => {
                        const match = trips.find((trip) => trip.orderId === order.id)
                        if (match) setSelectedTripId(match.id)
                        setScreen('auto-trip')
                      }}
                      className="w-full py-2 bg-primary text-white text-xs font-bold rounded-lg hover:opacity-90 transition-all"
                    >
                      Open Trip
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>

        <section className="bg-surface-container-lowest rounded-xl shadow-sm overflow-hidden border border-black/5">
          <div className="p-6 border-b border-black/5 flex items-center justify-between">
            <h3 className="text-lg font-bold tracking-tight">Ongoing Trips</h3>
            <span className="px-3 py-1 bg-surface-container-low rounded-full text-[11px] font-bold">Real-time Stream</span>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full min-w-[680px] text-left border-collapse">
              <thead>
                <tr className="bg-surface-container-low/50">
                  <th className="px-6 py-4 text-[10px] font-bold text-on-surface-variant uppercase tracking-wider">Trip ID</th>
                  <th className="px-6 py-4 text-[10px] font-bold text-on-surface-variant uppercase tracking-wider">Driver</th>
                  <th className="px-6 py-4 text-[10px] font-bold text-on-surface-variant uppercase tracking-wider">Status</th>
                  <th className="px-6 py-4 text-[10px] font-bold text-on-surface-variant uppercase tracking-wider">Current Location</th>
                  <th className="px-6 py-4 text-[10px] font-bold text-on-surface-variant uppercase tracking-wider text-right">Progress</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-black/5">
                {trips.map((trip) => {
                  const progress = trip.status === 'in_transit' ? 70 : trip.status === 'assigned' ? 35 : trip.status === 'completed' ? 100 : 15
                  return (
                    <tr key={trip.id} className="hover:bg-surface-container-low transition-colors">
                      <td className="px-6 py-4 text-xs font-bold">TRK-{trip.id}</td>
                      <td className="px-6 py-4 text-xs font-medium">{trip.driver?.name || 'Unassigned'}</td>
                      <td className="px-6 py-4 text-xs font-semibold">
                        <span className={`${trip.status === 'in_transit' ? 'text-error' : 'text-on-surface'}`}>{trip.status.replace('_', ' ')}</span>
                      </td>
                      <td className="px-6 py-4 text-xs text-on-surface-variant">{trip.order?.pickupLocation || '-'} </td>
                      <td className="px-6 py-4 text-right">
                        <div className="w-24 bg-surface-container rounded-full h-1 ml-auto">
                          <div className={`h-full rounded-full ${trip.status === 'in_transit' ? 'bg-error' : 'bg-primary'}`} style={{ width: `${progress}%` }} />
                        </div>
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        </section>
      </div>

      <aside className="w-full xl:w-80 shrink-0 space-y-6">
        <section className="bg-surface-container-low p-6 rounded-2xl border border-black/5">
          <h3 className="text-sm font-extrabold uppercase tracking-widest text-on-surface mb-4">Create Shipment</h3>
          {actionError ? <p className="mb-3 text-sm font-semibold text-on-error-container bg-error-container px-3 py-2 rounded-lg">{actionError}</p> : null}
          <form className="space-y-3" onSubmit={handleCreateOrder}>
            <Input label="Pickup" value={form.pickupLocation} onChange={(value) => setForm((prev) => ({ ...prev, pickupLocation: value }))} />
            <Input label="Drop" value={form.dropLocation} onChange={(value) => setForm((prev) => ({ ...prev, dropLocation: value }))} />
            <Input label="Load" value={form.load} onChange={(value) => setForm((prev) => ({ ...prev, load: value }))} />
            <Input label="Date" value={form.date} onChange={(value) => setForm((prev) => ({ ...prev, date: value }))} />
            <button disabled={isLoading} className="w-full h-11 bg-primary text-white text-sm font-bold rounded-lg hover:opacity-90 disabled:opacity-60">
              {isLoading ? 'Creating...' : 'Create + Auto Assign'}
            </button>
          </form>
          <div className="mt-5 pt-5 border-t border-black/5 space-y-2">
            <p className="text-[11px] font-semibold uppercase tracking-wider text-on-surface-variant">Raw Message Intake (NLP)</p>
            <textarea
              className="w-full rounded-lg border border-outline-variant/30 p-3 text-sm min-h-20"
              placeholder="Example: Send 10 tons from Vizag to Hyderabad tomorrow"
              value={rawOrderText}
              onChange={(event) => setRawOrderText(event.target.value)}
            />
            <button
              disabled={isLoading || !rawOrderText.trim()}
              onClick={handleIngestRawOrder}
              className="w-full h-10 bg-secondary text-on-secondary rounded-lg text-sm font-bold disabled:opacity-60"
            >
              Ingest Message + Create Trip
            </button>
          </div>
        </section>

        <section className="bg-surface-container-low p-6 rounded-2xl border border-black/5">
          <h3 className="text-sm font-extrabold uppercase tracking-widest text-on-surface mb-4">System Exceptions</h3>
          <div className="space-y-4">
            {unresolvedAlerts.slice(0, 3).map((alert) => (
              <div key={alert.id} className="bg-surface-container-lowest p-4 rounded-xl border-l-4 border-error shadow-sm">
                <p className="text-[10px] font-bold text-error uppercase">{alert.type}</p>
                <p className="text-xs font-bold mt-1">{alert.message}</p>
                <p className="text-[11px] text-on-surface-variant mt-1">Trip TRK-{alert.tripId}</p>
                <button
                  className="mt-3 w-full py-1.5 bg-primary text-white text-[10px] font-bold rounded-lg"
                  onClick={() => handleApproveTrip(trips.find((trip) => trip.id === alert.tripId)?.id)}
                >
                  Open Trip
                </button>
              </div>
            ))}
            {unresolvedAlerts.length === 0 ? <p className="text-xs text-on-surface-variant">No active exceptions.</p> : null}
          </div>
        </section>
      </aside>
    </div>
  )
}

export default DashboardPage
